version: "3"
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: banking_db
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
volumes:
  mysql_data:
    driver: local
